

SELECT name, open_mode FROM v$pdbs;

CREATE PLUGGABLE DATABASE plsql_class2025db
  ADMIN USER sonia_plsqlauca_28352 IDENTIFIED BY 28352
  FILE_NAME_CONVERT = (
    'C:\APP\ARAJE\PRODUCT\21C\ORADATA\XE\PDBSEED\',
    'C:\APP\ARAJE\PRODUCT\21C\ORADATA\XE\plsql_class2025db\'
  );

CREATE PLUGGABLE DATABASE di_to_delete_pdb_28352
  ADMIN USER sonia_plsqlauca_28352 IDENTIFIED BY 28352
  FILE_NAME_CONVERT = (
    'C:\APP\ARAJE\PRODUCT\21C\ORADATA\XE\PDBSEED\',
    'C:\APP\ARAJE\PRODUCT\21C\ORADATA\XE\di_to_delete_pdb_28352\'
  );
  
DROP PLUGGABLE DATABASE di_to_delete_pdb_28352 INCLUDING DATAFILES;






